In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('train.csv')

In [11]:
df.head()

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option,Units_Sold,Revenue
0,2023-07,Oceania,Toyota,i4,Crossover,62,6,High Income,No,260,3699780
1,2023-03,Oceania,Toyota,Leaf,Truck,70,19,High Income,Yes,347,7801424
2,2023-05,North America,Toyota,ID.5,Crossover,81,13,Middle Income,No,294,4813013
3,2023-02,Oceania,Tesla,Corolla EV,Truck,73,4,High Income,Yes,281,7484912
4,2023-10,North America,BYD,Leaf,Coupe,52,4,High Income,No,166,4025360

In [12]:
df.shape

(531, 11)

In [13]:
df.head(10)

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option,Units_Sold,Revenue
0,2023-07,Oceania,Toyota,i4,Crossover,62,6,High Income,No,260,3699780
1,2023-03,Oceania,Toyota,Leaf,Truck,70,19,High Income,Yes,347,7801424
2,2023-05,North America,Toyota,ID.5,Crossover,81,13,Middle Income,No,294,4813013
3,2023-02,Oceania,Tesla,Corolla EV,Truck,73,4,High Income,Yes,281,7484912
4,2023-10,North America,BYD,Leaf,Coupe,52,4,High Income,No,166,4025360
5,2023-03,South America,Tesla,i4,Sedan,59,17,Budget Conscious,Yes,204,3250425
6,2023-06,North America,Ford,Leaf,Hatchback,68,1,Middle Income,Yes,145,2879105
7,2023-07,South America,BMW,Rio EV,Sedan,54,7,Middle Income,Yes,389,6866527
8,2023-06,North America,Kia,i4,Sedan,51,14,High Income,No,278,4684608
9,2023-07,North America,BYD,Leaf,Hatchback,44,12,Tech Enthusiast,Yes,152,2669600

In [14]:
df.tail()

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option,Units_Sold,Revenue
526,2023-08,Oceania,Nissan,Ariya,Hatchback,81,14,High Income,Yes,109,2427852
527,2023-11,Asia,Hyundai,Ariya,Truck,48,3,High Income,No,362,7368396
528,2023-04,North America,BYD,Han EV,Hatchback,78,8,Budget Conscious,No,238,4893408
529,2023-05,Asia,Volkswagen,Model S,Crossover,43,5,High Income,No,205,4272600
530,2023-01,South America,Kia,Tucson EV,Hatchback,61,4,Budget Conscious,Yes,362,6608176

In [15]:
df.isnull().sum()

Date                    0
Region                  0
Brand                   0
Model                   0
Vehicle_Type            0
Battery_Capacity_kWh    0
Discount_Percentage     0
Customer_Segment        0
Fast_Charging_Option    0
Units_Sold              0
Revenue                 0
dtype: int64